In [187]:
# Collin County Public Records Scraper

"""
This notebook scrapes probate records from Collin County's public search portal.

Target URL: https://collin.tx.publicsearch.us/results?department=RP&keywordSearch=false&limit=50&offset=0&recordedDateRange=18930107%2C20260123&searchOcrText=false&searchType=quickSearch&searchValue=probate&sort=desc&sortBy=recordedDate
"""

# Cell 1: Setup and Imports
import pandas as pd
import time
import json
from datetime import datetime, timedelta
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import requests
from bs4 import BeautifulSoup
import re

print("Libraries imported successfully!")

Libraries imported successfully!

In [188]:
# Cell 2: Configuration
# Base URL for Collin County public records
BASE_URL = "https://collin.tx.publicsearch.us"

# Search parameters
SEARCH_PARAMS = {
    "department": "RP",
    "keywordSearch": "false",
    "limit": "50",
    "offset": "0",
    "recordedDateRange": "18930107,20260123",
    "searchOcrText": "false",
    "searchType": "quickSearch",
    "searchValue": "probate",
    "sort": "desc",
    "sortBy": "recordedDate"
}

# Selenium configuration
CHROME_OPTIONS = Options()
CHROME_OPTIONS.add_argument("--headless")  # Run in background
CHROME_OPTIONS.add_argument("--no-sandbox")
CHROME_OPTIONS.add_argument("--disable-dev-shm-usage")
CHROME_OPTIONS.add_argument("--disable-gpu")
CHROME_OPTIONS.add_argument("--window-size=1920,1080")
CHROME_OPTIONS.add_argument("--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# Wait times (in seconds)
PAGE_LOAD_WAIT = 10
ELEMENT_WAIT = 5

print("Configuration set up!")

Configuration set up!

In [189]:
# Cell 3: Initialize WebDriver
def initialize_driver():
    """Initialize Chrome WebDriver with configured options"""
    try:
        service = Service(ChromeDriverManager().install())
        driver = webdriver.Chrome(service=service, options=CHROME_OPTIONS)
        driver.set_page_load_timeout(30)
        print("WebDriver initialized successfully!")
        return driver
    except Exception as e:
        print(f"Error initializing WebDriver: {e}")
        return None

# Initialize the driver
driver = initialize_driver()

WebDriver initialized successfully!

In [190]:
# Cell 4: URL Builder and Page Loader
def build_search_url(params, offset=0):
    """Build search URL with given parameters and offset"""
    url_params = params.copy()
    url_params["offset"] = str(offset)
    
    query_string = "&".join([f"{k}={v}" for k, v in url_params.items()])
    return f"{BASE_URL}/results?{query_string}"

def load_page(driver, url, wait_time=PAGE_LOAD_WAIT):
    """Load a page and wait for it to complete"""
    try:
        print(f"Loading page: {url[:100]}...")
        driver.get(url)
        time.sleep(wait_time)
        
        # Wait for page to be ready
        WebDriverWait(driver, 25).until(
            EC.presence_of_element_located((By.TAG_NAME, "body"))
        )
        
        print(f"Page loaded successfully. Title: {driver.title}")
        return True
        
    except Exception as e:
        print(f"Error loading page: {e}")
        return False

# Test URL building
test_url = build_search_url(SEARCH_PARAMS, offset=0)
print(f"Test URL: {test_url}")

Test URL: https://collin.tx.publicsearch.us/results?department=RP&keywordSearch=false&limit=50&offset=0&recordedDateRange=18930107,20260123&searchOcrText=false&searchType=quickSearch&searchValue=probate&sort=desc&sortBy=recordedDate

In [191]:
def has_more_pages(driver, current_offset, limit=50):
    """Check if there are more pages by looking for fewer results than expected"""
    try:
        # Count actual records on current page
        record_selectors = [
            ".record",
            ".result-item", 
            ".search-result",
            "tr.record-row",
            ".data-row",
            "[data-record]",
            ".result"
        ]
        
        actual_count = 0
        for selector in record_selectors:
            try:
                elements = driver.find_elements(By.CSS_SELECTOR, selector)
                if elements:
                    actual_count = len(elements)
                    break
            except:
                continue
        
        # If we got fewer results than the limit, we're likely at the end
        if actual_count < limit:
            print(f"Found {actual_count} records (less than limit {limit}), likely at end")
            return False
        
        # Additional check: look for "no results" or "end of results" messages
        no_results_selectors = [
            ".no-results",
            ".no-more-results",
            ".end-of-results",
            "[data-no-results]"
        ]
        
        for selector in no_results_selectors:
            try:
                element = driver.find_element(By.CSS_SELECTOR, selector)
                if element.is_displayed():
                    print("Found 'no more results' indicator")
                    return False
            except:
                continue
        
        return True
        
    except Exception as e:
        print(f"Error checking for more pages: {e}")
        return False

In [196]:
# Cell 6: Page Data Extraction Function
def get_total_results(driver):
    """Find and extract the total results count from the Search Result Totals span"""
    try:
        # Find the span element with aria-label="Search Result Totals"
        element = driver.find_element(By.CSS_SELECTOR, 'span[aria-label="Search Result Totals"]')
        
        if element:
            # Get the innerText
            inner_text = element.text.strip()
            print(f"Found Search Result Totals span: '{inner_text}'")
            
            # Look for the pattern "1-50 of 6,720 results for"
            # We need to extract the number after "of" and before "results"
            import re
            
            # Pattern to match "of X,XXX results"
            pattern = r'of\s+(\d{1,2},?\d{3})\s+results'
            match = re.search(pattern, inner_text, re.IGNORECASE)
            
            if match:
                total_text = match.group(1)  # This will be "6,720"
                total_results = int(total_text.replace(',', ''))  # Convert to 6720
                print(f"Total results found: {total_results:,}")
                return total_results
            else:
                # Alternative: split by "of" and "results"
                if "of" in inner_text and "results" in inner_text:
                    parts = inner_text.split("of")[1].split("results")[0].strip()
                    total_results = int(parts.replace(',', ''))
                    print(f"Total results found (alternative method): {total_results:,}")
                    return total_results
                else:
                    print(f"Could not find 'of X results' pattern in: {inner_text}")
                    return None
        else:
            print("Search Result Totals span element not found")
            return None
            
    except Exception as e:
        print(f"Error finding total results: {e}")
        return None

def extract_page_data(driver):
    """Extract all record data from the current page and return records array"""
    records = []
    
    try:
        # Get total results first
        total_results = get_total_results(driver)
        
        # First try to find table rows (most structured approach)
        tables = driver.find_elements(By.TAG_NAME, "table")
        for table in tables:
            rows = table.find_elements(By.TAG_NAME, "tr")
            if len(rows) > 2:  # Need at least header + 2 data rows
                print(f"Found table with {len(rows)} rows")
                
                # Skip first two rows (header row + empty row), process data rows
                for i, row in enumerate(rows[2:], 1):  # Skip first two rows
                    try:
                        # Extract specific fields using CSS selectors
                        record_data = {}
                        
                        # Grantor field - <td class="col-3" column="[object Object]"><span>
                        grantor_elem = row.find_element(By.CSS_SELECTOR, 'td.col-3[column="[object Object]"] span')
                        record_data['grantor'] = grantor_elem.text.strip() if grantor_elem else ""
                        
                        # Grantee field - <td class="col-4" column="[object Object]"><span>
                        grantee_elem = row.find_element(By.CSS_SELECTOR, 'td.col-4[column="[object Object]"] span')
                        record_data['grantee'] = grantee_elem.text.strip() if grantee_elem else ""
                        
                        # Doc Type field - <td class="col-5" column="[object Object]"><span><em>
                        doc_type_elem = row.find_element(By.CSS_SELECTOR, 'td.col-5[column="[object Object]"] span em')
                        record_data['doc_type'] = doc_type_elem.text.strip() if doc_type_elem else ""
                        
                        # Recorded Date field - <td class="col-6" column="[object Object]"><span>
                        recorded_date_elem = row.find_element(By.CSS_SELECTOR, 'td.col-6[column="[object Object]"] span')
                        record_data['recorded_date'] = recorded_date_elem.text.strip() if recorded_date_elem else ""
                        
                        # Doc Number field - <td class="col-7" column="[object Object]"><span>
                        doc_number_elem = row.find_element(By.CSS_SELECTOR, 'td.col-7[column="[object Object]"] span')
                        record_data['doc_number'] = doc_number_elem.text.strip() if doc_number_elem else ""
                        
                        # Book/Volume/Page field - <td class="col-8" column="[object Object]"><span>
                        book_volume_elem = row.find_element(By.CSS_SELECTOR, 'td.col-8[column="[object Object]"] span')
                        record_data['book_volume_page'] = book_volume_elem.text.strip() if book_volume_elem else ""
                        
                        # Legal Description field - <td class="col-9" column="[object Object]"><span class="css-1dro08k">
                        legal_desc_elem = row.find_element(By.CSS_SELECTOR, 'td.col-9')
                        record_data['legal_description'] = legal_desc_elem.text.strip() if legal_desc_elem else ""
                        
                        # Add metadata
                        record_data['record_number'] = i
                        record_data['extracted_at'] = datetime.now().isoformat()
                        
                        print(f"Row {i} - Grantor: {record_data['grantor'][:50]}...")
                        print(f"Row {i} - Recorded Date: {record_data['recorded_date']}")
                        
                        records.append(record_data)
                        
                    except Exception as e:
                        print(f"Error extracting data from row {i}: {e}")
                        # Continue with next row
                        continue
                
                if records:
                    break
        
        print(f"Extracted {len(records)} records from page")
        
        # Show sample of extracted data for debugging
        if records:
            print(f"Sample record keys: {list(records[0].keys())}")
            # Show first few records for verification
            for i, record in enumerate(records[:2]):
                print(f"Record {i+1}: {record}")
        
        return records
        
    except Exception as e:
        print(f"Error extracting page data: {e}")
        return []

In [197]:
# Cell 7: Main Scraping Function using Offset Pagination
def scrape_collin_county_records(max_pages=10, delay_between_pages=10):
    """Main scraping function using offset-based pagination"""
    all_records = []
    
    try:
        # Initialize driver
        driver = initialize_driver()
        if not driver:
            return []
        
        # Pagination settings
        limit = int(SEARCH_PARAMS["limit"])
        current_offset = 0
        page_num = 1
        
        while page_num <= max_pages:
            print(f"\n=== Scraping Page {page_num} (offset: {current_offset}) ===")
            
            # Build URL with current offset
            page_url = build_search_url(SEARCH_PARAMS, offset=current_offset)
            
            # Load page
            if not load_page(driver, page_url):
                print(f"Failed to load page {page_num}")
                break
            
            # Extract data from current page
            page_records = extract_page_data(driver)
            
            if page_records:
                # Add page number and offset to each record
                for record in page_records:
                    record['page_number'] = page_num
                    record['offset'] = current_offset
                
                all_records.extend(page_records)
                print(f"Extracted {len(page_records)} records from page {page_num}")
            else:
                print("No records found on this page")
                # If no records found, we might be at the end
                break
            
            # Check if there are more pages
            if not has_more_pages(driver, current_offset, limit):
                print("No more pages available")
                break
            
            # Increment offset for next page
            current_offset += limit
            page_num += 1
            
            # Wait between pages
            time.sleep(delay_between_pages)
        
        print(f"\n=== Scraping Complete ===")
        print(f"Total records scraped: {len(all_records)}")
        print(f"Total pages scraped: {page_num - 1}")
        print(f"Final offset: {current_offset}")
        
        return all_records
        
    except Exception as e:
        print(f"Error during scraping: {e}")
        return all_records
    
    finally:
        if 'driver' in locals():
            driver.quit()
            print("WebDriver closed")

In [198]:
# Cell 8: Data Processing and Export
def process_and_export_data(records, filename_prefix="collin_county_probate"):
    """Process scraped data and export to CSV format"""
    if not records:
        print("No records to process")
        return
    
    # Convert to DataFrame
    df = pd.DataFrame(records)
    
    # Add processing timestamp
    df['processed_at'] = datetime.now().isoformat()
    
    # Display basic statistics
    print(f"\n=== Data Summary ===")
    print(f"Total records: {len(df)}")
    print(f"Columns: {list(df.columns)}")
    print(f"\nFirst few records:")
    display(df.head())
    
    # Create data directory if it doesn't exist
    import os
    data_dir = "data"
    if not os.path.exists(data_dir):
        os.makedirs(data_dir)
        print(f"Created directory: {data_dir}")
    
    # Generate date-based filename in data folder
    csv_filename = os.path.join(data_dir, f"{datetime.now().strftime('%Y-%m-%d')}-probate-records.csv")
    
    # Export to CSV
    df.to_csv(csv_filename, index=False)
    print(f"\nData exported to: {csv_filename}")
    
    return df

In [200]:
# Cell 9: Run the Scraper
# Configure scraping parameters
MAX_PAGES = 5  # Adjust as needed
DELAY_BETWEEN_PAGES = 3  # Seconds between requests

print("Starting Collin County probate records scraper...")
print(f"Max pages to scrape: {MAX_PAGES}")
print(f"Delay between pages: {DELAY_BETWEEN_PAGES} seconds")
print(f"Using offset-based pagination with limit: {SEARCH_PARAMS['limit']}")

# Run the scraper
scraped_records = scrape_collin_county_records(
    max_pages=MAX_PAGES,
    delay_between_pages=DELAY_BETWEEN_PAGES
)

df = process_and_export_data(scraped_records)
df

Starting Collin County probate records scraper...
Max pages to scrape: 5
Delay between pages: 3 seconds
Using offset-based pagination with limit: 50
WebDriver initialized successfully!

=== Scraping Page 1 (offset: 0) ===
Loading page: https://collin.tx.publicsearch.us/results?department=RP&keywordSearch=false&limit=50&offset=0&record...
Page loaded successfully. Title: Search Results
Found Search Result Totals span: '1-50 of 6,720 results for'
Total results found: 6,720
Found table with 52 rows
Row 1 - Grantor: GOYAL MADAN DECEASED ESTATE...
Row 1 - Recorded Date: 1/23/2026
Row 2 - Grantor: CHERRY ERIKA WOOD DECEASED ESTATE...
Row 2 - Recorded Date: 1/23/2026
Row 3 - Grantor: KING L M JR DECEASED ESTATE...
Row 3 - Recorded Date: 1/21/2026
Row 4 - Grantor: KIM JUNGJI DECEASED ESTATE...
Row 4 - Recorded Date: 1/21/2026
Row 5 - Grantor: HINCKLEY BONNIE YVONNE DECEASED ESTATE...
Row 5 - Recorded Date: 1/20/2026
Row 6 - Grantor: ROYAL COKE DECEASED ESTATE...
Row 6 - Recorded Date: 1/16/2026
Row 7 - Grantor: MALONE MARK ALLAN DECEASED ESTATE...
Row 7 - Recorded Date: 1/16/2026
Row 8 - Grantor: CADY ARMANDINA RUIZ DECEASED ESTATE...
Row 8 - Recorded Date: 1/13/2026
Row 9 - Grantor: BLOYS BARBARA JANE WEATHERS DECEASED ESTATE...
Row 9 - Recorded Date: 1/13/2026
Row 10 - Grantor: WAGNER CYNTHIA DIANE DECEASED ESTATE...
Row 10 - Recorded Date: 1/13/2026
Row 11 - Grantor: BLUME BRIAN LEE DECEASED ESTATE...
Row 11 - Recorded Date: 1/13/2026
Row 12 - Grantor: BAKSA PENNY T DECEASED ESTATE...
Row 12 - Recorded Date: 1/9/2026
Row 13 - Grantor: ELLIS RAYMOND M DECEASED ESTATE...
Row 13 - Recorded Date: 1/9/2026
Row 14 - Grantor: TULLOUS ALVIN LESTER DECEASED ESTATE...
Row 14 - Recorded Date: 1/9/2026
Row 15 - Grantor: O'TOOLE JAMES DECEASED ESTATE...
Row 15 - Recorded Date: 1/9/2026
Row 16 - Grantor: NEWSOME TERI L DECEASED ESTATE...
Row 16 - Recorded Date: 1/8/2026
Row 17 - Grantor: HICKMAN WANDA ELOISE DECEASED ESTATE...
Row 17 - Recorded Date: 1/7/2026
Row 18 - Grantor: DOWDY MARY ELIZABETH DECEASED ESTATE...
Row 18 - Recorded Date: 1/7/2026
Row 19 - Grantor: GRAHAM WILLIAM DECEASED ESTATE...
Row 19 - Recorded Date: 1/5/2026
Row 20 - Grantor: SUTTON DAVID MICHAEL DECEASED ESTATE...
Row 20 - Recorded Date: 1/2/2026
Row 21 - Grantor: CLOE GLOYD F DECEASED ESTATE...
Row 21 - Recorded Date: 12/31/2025
Row 22 - Grantor: MAIER LOTHAR THOMAS DECEASED ESTATE...
Row 22 - Recorded Date: 12/31/2025
Row 23 - Grantor: PRYOR HARRY E DECEASED ESTATE...
Row 23 - Recorded Date: 12/22/2025
Row 24 - Grantor: WILLIAMS RONALD DECEASED ESTATE...
Row 24 - Recorded Date: 12/19/2025
Row 25 - Grantor: HOLLOWAY EARL DECEASED ESTATE...
Row 25 - Recorded Date: 12/19/2025
Row 26 - Grantor: HOLMAN LOUVENIA DECEASED ESTATE...
Row 26 - Recorded Date: 12/19/2025
Row 27 - Grantor: GALLETTA JESSICA ANN DECEASED ESTATE...
Row 27 - Recorded Date: 12/17/2025
Row 28 - Grantor: HOLMAN BOBBY L DECEASED ESTATE...
Row 28 - Recorded Date: 12/17/2025
Row 29 - Grantor: VASINDA JULIA CONGETTA DECEASED ESTATE...
Row 29 - Recorded Date: 12/16/2025
Row 30 - Grantor: VASINDA RAYMOND JOHN SR DECEASED ESTATE...
Row 30 - Recorded Date: 12/15/2025
Row 31 - Grantor: KUBIN JOHN WILLIAM DECEASED ESTATE...
Row 31 - Recorded Date: 12/12/2025
Row 32 - Grantor: KUBIN MARY FRANCES DECEASED ESTATE...
Row 32 - Recorded Date: 12/12/2025
Row 33 - Grantor: PARKER LYNDA KAY DECEASED ESTATE...
Row 33 - Recorded Date: 12/12/2025
Row 34 - Grantor: ALSUP LYNN DECEASED ESTATE...
Row 34 - Recorded Date: 12/12/2025
Error extracting data from row 35: Message: no such element: Unable to locate element: {"method":"css selector","selector":"td.col-5[column="[object Object]"] span em"}
  (Session info: chrome=144.0.7559.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x0000000104f02fd4 cxxbridge1$str$ptr + 3095476
1   chromedriver                        0x0000000104efb3ec cxxbridge1$str$ptr + 3063756
2   chromedriver                        0x00000001049de83c _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 75008
3   chromedriver                        0x0000000104a27d68 _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 375340
4   chromedriver                        0x0000000104a1d728 _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 332780
5   chromedriver                        0x0000000104a66fdc _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 634016
6   chromedriver                        0x0000000104a1c06c _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 326960
7   chromedriver                        0x0000000104ec15dc cxxbridge1$str$ptr + 2826684
8   chromedriver                        0x0000000104ec4d1c cxxbridge1$str$ptr + 2840828
9   chromedriver                        0x0000000104ea6bec cxxbridge1$str$ptr + 2717644
10  chromedriver                        0x0000000104ec55a0 cxxbridge1$str$ptr + 2843008
11  chromedriver                        0x0000000104e96cc4 cxxbridge1$str$ptr + 2652324
12  chromedriver                        0x0000000104ee9a9c cxxbridge1$str$ptr + 2991740
13  chromedriver                        0x0000000104ee9c18 cxxbridge1$str$ptr + 2992120
14  chromedriver                        0x0000000104efb044 cxxbridge1$str$ptr + 3062820
15  libsystem_pthread.dylib             0x0000000186121c08 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018611cba8 thread_start + 8

Error extracting data from row 36: Message: no such element: Unable to locate element: {"method":"css selector","selector":"td.col-5[column="[object Object]"] span em"}
  (Session info: chrome=144.0.7559.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x0000000104f02fd4 cxxbridge1$str$ptr + 3095476
1   chromedriver                        0x0000000104efb3ec cxxbridge1$str$ptr + 3063756
2   chromedriver                        0x00000001049de83c _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 75008
3   chromedriver                        0x0000000104a27d68 _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 375340
4   chromedriver                        0x0000000104a1d728 _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 332780
5   chromedriver                        0x0000000104a66fdc _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 634016
6   chromedriver                        0x0000000104a1c06c _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 326960
7   chromedriver                        0x0000000104ec15dc cxxbridge1$str$ptr + 2826684
8   chromedriver                        0x0000000104ec4d1c cxxbridge1$str$ptr + 2840828
9   chromedriver                        0x0000000104ea6bec cxxbridge1$str$ptr + 2717644
10  chromedriver                        0x0000000104ec55a0 cxxbridge1$str$ptr + 2843008
11  chromedriver                        0x0000000104e96cc4 cxxbridge1$str$ptr + 2652324
12  chromedriver                        0x0000000104ee9a9c cxxbridge1$str$ptr + 2991740
13  chromedriver                        0x0000000104ee9c18 cxxbridge1$str$ptr + 2992120
14  chromedriver                        0x0000000104efb044 cxxbridge1$str$ptr + 3062820
15  libsystem_pthread.dylib             0x0000000186121c08 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018611cba8 thread_start + 8

Error extracting data from row 37: Message: no such element: Unable to locate element: {"method":"css selector","selector":"td.col-5[column="[object Object]"] span em"}
  (Session info: chrome=144.0.7559.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x0000000104f02fd4 cxxbridge1$str$ptr + 3095476
1   chromedriver                        0x0000000104efb3ec cxxbridge1$str$ptr + 3063756
2   chromedriver                        0x00000001049de83c _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 75008
3   chromedriver                        0x0000000104a27d68 _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 375340
4   chromedriver                        0x0000000104a1d728 _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 332780
5   chromedriver                        0x0000000104a66fdc _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 634016
6   chromedriver                        0x0000000104a1c06c _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 326960
7   chromedriver                        0x0000000104ec15dc cxxbridge1$str$ptr + 2826684
8   chromedriver                        0x0000000104ec4d1c cxxbridge1$str$ptr + 2840828
9   chromedriver                        0x0000000104ea6bec cxxbridge1$str$ptr + 2717644
10  chromedriver                        0x0000000104ec55a0 cxxbridge1$str$ptr + 2843008
11  chromedriver                        0x0000000104e96cc4 cxxbridge1$str$ptr + 2652324
12  chromedriver                        0x0000000104ee9a9c cxxbridge1$str$ptr + 2991740
13  chromedriver                        0x0000000104ee9c18 cxxbridge1$str$ptr + 2992120
14  chromedriver                        0x0000000104efb044 cxxbridge1$str$ptr + 3062820
15  libsystem_pthread.dylib             0x0000000186121c08 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018611cba8 thread_start + 8

Row 38 - Grantor: PAYN JOHN KENNEDY DECEASED ESTATE...
Row 38 - Recorded Date: 12/5/2025
Row 39 - Grantor: RUIZ OLGA MARY DECEASED ESTATE...
Row 39 - Recorded Date: 12/4/2025
Row 40 - Grantor: VAN BUSKIRK JEFFREY STEVEN DECEASED ESTATE...
Row 40 - Recorded Date: 12/2/2025
Row 41 - Grantor: RED FRANCES DECEASED ESTATE...
Row 41 - Recorded Date: 11/25/2025
Row 42 - Grantor: JONES JOHN WILLIAM DECEASED ESTATE...
Row 42 - Recorded Date: 11/25/2025
Error extracting data from row 43: Message: no such element: Unable to locate element: {"method":"css selector","selector":"td.col-5[column="[object Object]"] span em"}
  (Session info: chrome=144.0.7559.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x0000000104f02fd4 cxxbridge1$str$ptr + 3095476
1   chromedriver                        0x0000000104efb3ec cxxbridge1$str$ptr + 3063756
2   chromedriver                        0x00000001049de83c _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 75008
3   chromedriver                        0x0000000104a27d68 _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 375340
4   chromedriver                        0x0000000104a1d728 _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 332780
5   chromedriver                        0x0000000104a66fdc _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 634016
6   chromedriver                        0x0000000104a1c06c _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 326960
7   chromedriver                        0x0000000104ec15dc cxxbridge1$str$ptr + 2826684
8   chromedriver                        0x0000000104ec4d1c cxxbridge1$str$ptr + 2840828
9   chromedriver                        0x0000000104ea6bec cxxbridge1$str$ptr + 2717644
10  chromedriver                        0x0000000104ec55a0 cxxbridge1$str$ptr + 2843008
11  chromedriver                        0x0000000104e96cc4 cxxbridge1$str$ptr + 2652324
12  chromedriver                        0x0000000104ee9a9c cxxbridge1$str$ptr + 2991740
13  chromedriver                        0x0000000104ee9c18 cxxbridge1$str$ptr + 2992120
14  chromedriver                        0x0000000104efb044 cxxbridge1$str$ptr + 3062820
15  libsystem_pthread.dylib             0x0000000186121c08 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018611cba8 thread_start + 8

Error extracting data from row 44: Message: no such element: Unable to locate element: {"method":"css selector","selector":"td.col-5[column="[object Object]"] span em"}
  (Session info: chrome=144.0.7559.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x0000000104f02fd4 cxxbridge1$str$ptr + 3095476
1   chromedriver                        0x0000000104efb3ec cxxbridge1$str$ptr + 3063756
2   chromedriver                        0x00000001049de83c _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 75008
3   chromedriver                        0x0000000104a27d68 _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 375340
4   chromedriver                        0x0000000104a1d728 _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 332780
5   chromedriver                        0x0000000104a66fdc _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 634016
6   chromedriver                        0x0000000104a1c06c _RNvCs5DBLTqoOdVp_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 326960
7   chromedriver                        0x0000000104ec15dc cxxbridge1$str$ptr + 2826684
8   chromedriver                        0x0000000104ec4d1c cxxbridge1$str$ptr + 2840828
9   chromedriver                        0x0000000104ea6bec cxxbridge1$str$ptr + 2717644
10  chromedriver                        0x0000000104ec55a0 cxxbridge1$str$ptr + 2843008
11  chromedriver                        0x0000000104e96cc4 cxxbridge1$str$ptr + 2652324
12  chromedriver                        0x0000000104ee9a9c cxxbridge1$str$ptr + 2991740
13  chromedriver                        0x0000000104ee9c18 cxxbridge1$str$ptr + 2992120
14  chromedriver                        0x0000000104efb044 cxxbridge1$str$ptr + 3062820
15  libsystem_pthread.dylib             0x0000000186121c08 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018611cba8 thread_start + 8

Row 45 - Grantor: ADAMS SCOTT M DECEASED ESTATE...
Row 45 - Recorded Date: 11/24/2025
Row 46 - Grantor: DOGGETT DONALD LEE DECEASED ESTATE...
Row 46 - Recorded Date: 11/21/2025
Row 47 - Grantor: COX STEPHEN R DECEASED ESTATE...
Row 47 - Recorded Date: 11/18/2025
Row 48 - Grantor: SMITH WILLIAM FERRIN JR DECEASED ESTATE...
Row 48 - Recorded Date: 11/18/2025
Row 49 - Grantor: DANA RONALD E DECEASED ESTATE...
Row 49 - Recorded Date: 11/14/2025
Row 50 - Grantor: BERG JEFFREY IAN DECEASED ESTATE...
Row 50 - Recorded Date: 11/11/2025
Extracted 45 records from page
Sample record keys: ['grantor', 'grantee', 'doc_type', 'recorded_date', 'doc_number', 'book_volume_page', 'legal_description', 'record_number', 'extracted_at']
Record 1: {'grantor': 'GOYAL MADAN DECEASED ESTATE', 'grantee': 'PUBLIC', 'doc_type': 'PROBATE', 'recorded_date': '1/23/2026', 'doc_number': '2026000009450', 'book_volume_page': '--/--/--', 'legal_description': 'N/A', 'record_number': 1, 'extracted_at': '2026-01-29T20:00:15.944810'}
Record 2: {'grantor': 'CHERRY ERIKA WOOD DECEASED ESTATE', 'grantee': 'PUBLIC', 'doc_type': 'PROBATE', 'recorded_date': '1/23/2026', 'doc_number': '2026000009280', 'book_volume_page': '--/--/--', 'legal_description': 'N/A', 'record_number': 2, 'extracted_at': '2026-01-29T20:00:15.989922'}
Extracted 45 records from page 1
Found 0 records (less than limit 50), likely at end
No more pages available

=== Scraping Complete ===
Total records scraped: 45
Total pages scraped: 0
Final offset: 0
WebDriver closed

=== Data Summary ===
Total records: 45
Columns: ['grantor', 'grantee', 'doc_type', 'recorded_date', 'doc_number', 'book_volume_page', 'legal_description', 'record_number', 'extracted_at', 'page_number', 'offset', 'processed_at']

First few records:

,grantor,grantee,doc_type,recorded_date,doc_number,book_volume_page,legal_description,record_number,extracted_at,page_number,offset,processed_at
0,GOYAL MADAN DECEASED ESTATE,PUBLIC,PROBATE,1/23/2026,2026000009450,--/--/--,N/A,1,2026-01-29T20:00:15.944810,1,0,2026-01-29T20:00:18.800686
1,CHERRY ERIKA WOOD DECEASED ESTATE,PUBLIC,PROBATE,1/23/2026,2026000009280,--/--/--,N/A,2,2026-01-29T20:00:15.989922,1,0,2026-01-29T20:00:18.800686
2,KING L M JR DECEASED ESTATE,PUBLIC,PROBATE,1/21/2026,2026000008491,--/--/--,N/A,3,2026-01-29T20:00:16.036722,1,0,2026-01-29T20:00:18.800686
3,KIM JUNGJI DECEASED ESTATE,PUBLIC,PROBATE,1/21/2026,2026000008179,--/--/--,Subdivision - Name: SMITH ESTATES FRISCO Lot: ...,4,2026-01-29T20:00:16.089897,1,0,2026-01-29T20:00:18.800686
4,HINCKLEY BONNIE YVONNE DECEASED ESTATE,PUBLIC,PROBATE,1/20/2026,2026000007253,--/--/--,N/A,5,2026-01-29T20:00:16.476293,1,0,2026-01-29T20:00:18.800686

Data exported to: data/2026-01-29-probate-records.csv

,grantor,grantee,doc_type,recorded_date,doc_number,book_volume_page,legal_description,record_number,extracted_at,page_number,offset,processed_at
0,GOYAL MADAN DECEASED ESTATE,PUBLIC,PROBATE,1/23/2026,2026000009450,--/--/--,N/A,1,2026-01-29T20:00:15.944810,1,0,2026-01-29T20:00:18.800686
1,CHERRY ERIKA WOOD DECEASED ESTATE,PUBLIC,PROBATE,1/23/2026,2026000009280,--/--/--,N/A,2,2026-01-29T20:00:15.989922,1,0,2026-01-29T20:00:18.800686
2,KING L M JR DECEASED ESTATE,PUBLIC,PROBATE,1/21/2026,2026000008491,--/--/--,N/A,3,2026-01-29T20:00:16.036722,1,0,2026-01-29T20:00:18.800686
3,KIM JUNGJI DECEASED ESTATE,PUBLIC,PROBATE,1/21/2026,2026000008179,--/--/--,Subdivision - Name: SMITH ESTATES FRISCO Lot: ...,4,2026-01-29T20:00:16.089897,1,0,2026-01-29T20:00:18.800686
4,HINCKLEY BONNIE YVONNE DECEASED ESTATE,PUBLIC,PROBATE,1/20/2026,2026000007253,--/--/--,N/A,5,2026-01-29T20:00:16.476293,1,0,2026-01-29T20:00:18.800686
5,ROYAL COKE DECEASED ESTATE,PUBLIC,PROBATE,1/16/2026,2026000006940,--/--/--,Subdivision - Name: MARTIN FARMS ST PAUL Lot: ...,6,2026-01-29T20:00:16.579838,1,0,2026-01-29T20:00:18.800686
6,MALONE MARK ALLAN DECEASED ESTATE,PUBLIC,PROBATE,1/16/2026,2026000006343,--/--/--,N/A,7,2026-01-29T20:00:16.638556,1,0,2026-01-29T20:00:18.800686
7,CADY ARMANDINA RUIZ DECEASED ESTATE,PUBLIC,PROBATE,1/13/2026,2026000004474,--/--/--,N/A,8,2026-01-29T20:00:16.688325,1,0,2026-01-29T20:00:18.800686
8,BLOYS BARBARA JANE WEATHERS DECEASED ESTATE,PUBLIC,PROBATE,1/13/2026,2026000004383,--/--/--,N/A,9,2026-01-29T20:00:16.736943,1,0,2026-01-29T20:00:18.800686
9,WAGNER CYNTHIA DIANE DECEASED ESTATE,PUBLIC,PROBATE,1/13/2026,2026000004382,--/--/--,N/A,10,2026-01-29T20:00:16.786405,1,0,2026-01-29T20:00:18.800686
10,BLUME BRIAN LEE DECEASED ESTATE,PUBLIC,PROBATE,1/13/2026,2026000004381,--/--/--,Subdivision - Name: HEIGHTS WESTRIDGE #3 MCKIN...,11,2026-01-29T20:00:16.832436,1,0,2026-01-29T20:00:18.800686
11,BAKSA PENNY T DECEASED ESTATE,PUBLIC,PROBATE,1/9/2026,2026000003441,--/--/--,N/A,12,2026-01-29T20:00:16.878705,1,0,2026-01-29T20:00:18.800686
12,ELLIS RAYMOND M DECEASED ESTATE,PUBLIC,PROBATE,1/9/2026,2026000003438,--/--/--,N/A,13,2026-01-29T20:00:16.927531,1,0,2026-01-29T20:00:18.800686
13,TULLOUS ALVIN LESTER DECEASED ESTATE,PUBLIC,PROBATE,1/9/2026,2026000003234,--/--/--,N/A,14,2026-01-29T20:00:16.973336,1,0,2026-01-29T20:00:18.800686
14,O'TOOLE JAMES DECEASED ESTATE,PUBLIC,PROBATE,1/9/2026,2026000002969,--/--/--,N/A,15,2026-01-29T20:00:17.019205,1,0,2026-01-29T20:00:18.800686
15,NEWSOME TERI L DECEASED ESTATE,PUBLIC,PROBATE,1/8/2026,2026000002777,--/--/--,N/A,16,2026-01-29T20:00:17.064474,1,0,2026-01-29T20:00:18.800686
16,HICKMAN WANDA ELOISE DECEASED ESTATE,PUBLIC,PROBATE,1/7/2026,2026000002259,--/--/--,N/A,17,2026-01-29T20:00:17.111448,1,0,2026-01-29T20:00:18.800686
17,DOWDY MARY ELIZABETH DECEASED ESTATE,PUBLIC,PROBATE,1/7/2026,2026000001908,--/--/--,N/A,18,2026-01-29T20:00:17.163554,1,0,2026-01-29T20:00:18.800686
18,GRAHAM WILLIAM DECEASED ESTATE,PUBLIC,PROBATE,1/5/2026,2026000000950,--/--/--,N/A,19,2026-01-29T20:00:17.209438,1,0,2026-01-29T20:00:18.800686
19,SUTTON DAVID MICHAEL DECEASED ESTATE,PUBLIC,PROBATE,1/2/2026,2026000000421,--/--/--,N/A,20,2026-01-29T20:00:17.257890,1,0,2026-01-29T20:00:18.800686
20,CLOE GLOYD F DECEASED ESTATE,PUBLIC,PROBATE,12/31/2025,2025000169069,--/--/--,N/A,21,2026-01-29T20:00:17.309706,1,0,2026-01-29T20:00:18.800686
21,MAIER LOTHAR THOMAS DECEASED ESTATE,PUBLIC,PROBATE,12/31/2025,2025000168865,--/--/--,N/A,22,2026-01-29T20:00:17.361382,1,0,2026-01-29T20:00:18.800686
22,PRYOR HARRY E DECEASED ESTATE,PUBLIC,PROBATE,12/22/2025,2025000165006,--/--/--,N/A,23,2026-01-29T20:00:17.418561,1,0,2026-01-29T20:00:18.800686
23,WILLIAMS RONALD DECEASED ESTATE,PUBLIC,PROBATE,12/19/2025,2025000164497,--/--/--,N/A,24,2026-01-29T20:00:17.474161,1,0,2026-01-29T20:00:18.800686
24,HOLLOWAY EARL DECEASED ESTATE,PUBLIC,PROBATE,12/19/2025,2025000164307,--/--/--,N/A,25,2026-01-29T20:00:17.523664,1,0,2026-01-29T20:00:18.800686
25,HOLMAN LOUVENIA DECEASED ESTATE,PUBLIC,PROBATE,12/19/2025,2025000164034,--/--/--,SEE INSTRUMENT,26,2026-01-29T20:00:17.571124,1,0,2026-01-29T20:00:18.800686
26,GALLETTA JESSICA ANN DECEASED ESTATE,PUBLIC,PROBATE,12/17/2025,2025000162979,--/--/--,N/A,27,2026-01-29T20:00:17.619182,1,0,2026-01-29T20:00:18.800686
27,HOLMAN BOBBY L DECEASED ESTATE,PUBLIC,PROBATE,12/17/2025,2025000162844,--/--/--,Subdivision - Name: MEADOWS #1 PLANO Lot: 34A ...,28,2026-01-29T20:00:17.668202,1,0,2026-01-29T20:00:18.800686
28,VASINDA JULIA CONGETTA DECEASED ESTATE,PUBLIC,PROBATE,12/16/2025,2025000161955,--/--/--,N/A,29,2026-01-29T20:00:17.717141,1,0,2026-01-29T20:00:18.800686
29,VASINDA RAYMOND JOHN SR DECEASED ESTATE,PUBLIC,PROBATE,12/15/2025,2025000161774,--/--/--,N/A,30,2026-01-29T20:00:17.765698,1,0,2026-01-29T20:00:18.800686
30,KUBIN JOHN WILLIAM DECEASED ESTATE,PUBLIC,PROBATE,12/12/2025,2025000160928,--/--/--,Survey - Acres: 82.36,31,2026-01-29T20:00:17.817471,1,0,2026-01-29T20:00:18.800686
31,KUBIN MARY FRANCES DECEASED ESTATE,PUBLIC,PROBATE,12/12/2025,2025000160929,--/--/--,Survey - Acres: 82.36,32,2026-01-29T20:00:17.865729,1,0,2026-01-29T20:00:18.800686
32,PARKER LYNDA KAY DECEASED ESTATE,PUBLIC,PROBATE,12/12/2025,2025000160609,--/--/--,N/A,33,2026-01-29T20:00:17.912548,1,0,2026-01-29T20:00:18.800686
33,ALSUP LYNN DECEASED ESTATE,PUBLIC,PROBATE,12/12/2025,2025000160305,--/--/--,Subdivision - Name: WHIFFLETREE #6 PLANO Lot: ...,34,2026-01-29T20:00:17.961763,1,0,2026-01-29T20:00:18.800686
34,PAYN JOHN KENNEDY DECEASED ESTATE,PUBLIC,PROBATE,12/5/2025,2025000157229,--/--/--,Subdivision - Name: HERITAGE PARK #1 ALLEN Lot...,38,2026-01-29T20:00:18.068513,1,0,2026-01-29T20:00:18.800686
35,RUIZ OLGA MARY DECEASED ESTATE,PUBLIC,PROBATE,12/4/2025,2025000156904,--/--/--,N/A,39,2026-01-29T20:00:18.116016,1,0,2026-01-29T20:00:18.800686
36,VAN BUSKIRK JEFFREY STEVEN DECEASED ESTATE,PUBLIC,PROBATE,12/2/2025,2025000155631,--/--/--,N/A,40,2026-01-29T20:00:18.167881,1,0,2026-01-29T20:00:18.800686
37,RED FRANCES DECEASED ESTATE,PUBLIC,PROBATE,11/25/2025,2025000152758,--/--/--,N/A,41,2026-01-29T20:00:18.220380,1,0,2026-01-29T20:00:18.800686
38,JONES JOHN WILLIAM DECEASED ESTATE,PUBLIC,PROBATE,11/25/2025,2025000152640,--/--/--,N/A,42,2026-01-29T20:00:18.273862,1,0,2026-01-29T20:00:18.800686
39,ADAMS SCOTT M DECEASED ESTATE,PUBLIC,PROBATE,11/24/2025,2025000151776,--/--/--,N/A,45,2026-01-29T20:00:18.359332,1,0,2026-01-29T20:00:18.800686
40,DOGGETT DONALD LEE DECEASED ESTATE,PUBLIC,PROBATE,11/21/2025,2025000151321,--/--/--,N/A,46,2026-01-29T20:00:18.408312,1,0,2026-01-29T20:00:18.800686
41,COX STEPHEN R DECEASED ESTATE,PUBLIC,PROBATE,11/18/2025,2025000149171,--/--/--,N/A,47,2026-01-29T20:00:18.458057,1,0,2026-01-29T20:00:18.800686
42,SMITH WILLIAM FERRIN JR DECEASED ESTATE,PUBLIC,PROBATE,11/18/2025,2025000149071,--/--/--,N/A,48,2026-01-29T20:00:18.509492,1,0,2026-01-29T20:00:18.800686
43,DANA RONALD E DECEASED ESTATE,PUBLIC,PROBATE,11/14/2025,2025000147807,--/--/--,N/A,49,2026-01-29T20:00:18.559298,1,0,2026-01-29T20:00:18.800686
44,BERG JEFFREY IAN DECEASED ESTATE,PUBLIC,PROBATE,11/11/2025,2025000146337,--/--/--,N/A,50,2026-01-29T20:00:18.605715,1,0,2026-01-29T20:00:18.800686

In [186]:
df.columns

Index(['plain_text', 'html_content', 'record_number', 'extracted_at'], dtype='str')